# Generated by Django 6.0 on 2025-12-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('artigo', 'Artigo'), ('ensaio', 'Ensaio'), ('resenha', 'Resenha'), ('recomendacao', 'Recomendação Bibliográfica'), ('multimidia', 'Multimídia')], default='artigo', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vídeo para conteúdo multimídia', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
    ]
