# Generated by Django 6.0 on 2025-12-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_category_article_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
