# Generated by Django 6.0 on 2025-12-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Ensaio',
            fields=[
            ],
            options={
                'verbose_name': 'Ensaio',
                'verbose_name_plural': 'Ensaios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Multimidia',
            fields=[
            ],
            options={
                'verbose_name': 'Multimídia',
                'verbose_name_plural': 'Multimídia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
            ],
            options={
                'verbose_name': 'Resenha',
                'verbose_name_plural': 'Resenhas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.article',),
        ),
    ]
