# Generated by Django 6.0 on 2025-12-27 23:02

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson_duration_alter_lesson_vimeo_video_id_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.EncryptedFileSystemStorage(), upload_to='articles/pdfs/'),
        ),
    ]
