# Generated by Django 6.0 on 2025-12-29 02:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_article_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
