# Generated by Django 6.0 on 2025-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Dimensão recomendada: 510x539', upload_to='shop/covers/')),
                ('amazon_link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item da Loja',
                'verbose_name_plural': 'Itens da Loja',
                'ordering': ['order'],
            },
        ),
    ]
