# Generated by Django 6.0 on 2025-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visita Diária',
                'verbose_name_plural': 'Visitas Diárias',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
